default:
  tags:
    - docker

stages:
  - build

build:
  stage: build
  when: manual
  allow_failure: false
  image: docker:24.0.6
  services:
    - docker:24.0.6-dind
  before_script:
    - docker info
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - DOCKER_BUILDKIT=1 docker build --tag $CI_PROJECT_NAME:latest --file Dockerfile .
    - docker image ls | grep $CI_PROJECT_NAME
    - rm -f $CI_PROJECT_NAME:latest.tar
    - docker save -o $CI_PROJECT_NAME:latest.tar $CI_PROJECT_NAME:latest
  artifacts:
    when: on_success
    paths:
      - $CI_PROJECT_NAME:latest.tar
    expire_in: 7 days
