default:
  image: docker:24.0.6
  services:
    - docker:24.0.6-dind

variables:
  DOCKER_NAME: $CI_PROJECT_NAME:latest

stages:
  - build
  - push_to_registry

build:
  stage: build
  allow_failure: false
  before_script:
    - docker info
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - DOCKER_BUILDKIT=1 docker build --tag $DOCKER_NAME --file Dockerfile .
    - docker image ls | grep $CI_PROJECT_NAME
    - rm -f $CI_PROJECT_NAME:latest.tar
    - docker save -o $DOCKER_NAME.tar $DOCKER_NAME
  artifacts:
    when: on_success
    paths:
      - $DOCKER_NAME.tar
    expire_in: 7 days

push_to_registry:
  stage: push_to_registry
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $DOCKER_REGISTRY
    - docker load -i $DOCKER_NAME.tar
    - docker push $DOCKER_NAME