default:
  image: docker:24.0.6
  services:
    - docker:24.0.6-dind
  tags:
    - docker

variables:
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

stages:
  - build

build:
  stage: build
  allow_failure: false
  before_script:
    - docker info
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - DOCKER_BUILDKIT=1 docker build --tag $CONTAINER_RELEASE_IMAGE --file Dockerfile .
    - docker image ls | grep $CI_REGISTRY_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE